apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: runtime-component

resources:
  - runtime-component-crd.yaml
  - runtime-component-operator.yaml
  - runtime-component-roles.yaml
