apiVersion: apps/v1
kind: Deployment
metadata:
  name: runtime-component-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: runtime-component-operator
  template:
    metadata:
      labels:
        name: runtime-component-operator
    spec:
      serviceAccountName: runtime-component-operator
      containers:
        - name: runtime-component-operator
          image: applicationstacks/operator:daily
          command:
          - runtime-component-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "runtime-component-operator"
